if(typeof(window.Localizations) == 'undefined') window.Localizations = {};
if(typeof(window.Localizations.Common) == 'undefined') window.Localizations.Common = {};
if(typeof(window.Localizations.Common.Title) == 'undefined') window.Localizations.Common.Title = {};
window.Localizations.Common.Title.Listen = '收听';
window.Localizations.Common.Title.Photogallery = '图片汇集';
window.Localizations.Common.Title.Multimedia = '多媒体文档';
window.Localizations.Common.Title.Download = '下载';
window.Localizations.Common.Title.NoDataForDay = '本日没有数据';
window.Localizations.Common.Title.More = '更多';
window.Localizations.Common.Title.CloseWindow = '关闭';
window.Localizations.Common.Title.WatchVideo = '观看视频';
window.Localizations.Common.Title.MoreArticles = '更多文章';
window.Localizations.Common.Title.MoreNews = '更多新闻';
window.Localizations.Common.Title.Audio = '音频';
window.Localizations.Common.Title.View = '视图';
window.Localizations.Common.Title.SoundSlide = '音频演示';
window.Localizations.Common.Title.Advertisment = '网上服务：';
window.Localizations.Common.Title.MoreVideoWidget = '更多多媒体';
window.Localizations.Common.Title.Playlist = '播放';
window.Localizations.Common.Title.Video = '视频';
window.Localizations.Common.Title.Documents = '相关文档';
window.Localizations.Common.Title.Hide = 'Hide';
window.Localizations.Common.Title.LoadMore = '加载更多';
window.Localizations.Common.Title.ContentAuthor = 'Content Author page';
;